INSERT INTO christmas_menus (id, menu_data) VALUES
(1, '<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<polar_celebration version="3.0">
  <event_administration>
    <temporal_data>
      <calendar_details>
        <date_info>
          <year>2024</year>
          <month>12</month>
          <day>25</day>
        </date_info>
        <time_specifics>
          <start_time>18:00</start_time>
          <end_time>23:00</end_time>
        </time_specifics>
      </calendar_details>
    </temporal_data>
    <participant_metrics>
      <attendance_details>
        <headcount>
          <total_present>77</total_present>
          <divisions>
            <craft_division>45</craft_division>
            <logistics_division>32</logistics_division>
          </divisions>
        </headcount>
      </attendance_details>
    </participant_metrics>
    <culinary_records>
      <menu_analysis>
        <item_performance>
          <food_item_id>301</food_item_id>
          <success_metrics>
            <satisfaction_index>3.0</satisfaction_index>
            <reorder_probability>0.11981593305412996</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>271</food_item_id>
          <success_metrics>
            <satisfaction_index>3.9</satisfaction_index>
            <reorder_probability>0.730437990451365</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>267</food_item_id>
          <success_metrics>
            <satisfaction_index>2.4</satisfaction_index>
            <reorder_probability>0.5025128007481285</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>356</food_item_id>
          <success_metrics>
            <satisfaction_index>2.6</satisfaction_index>
            <reorder_probability>0.3016942504669261</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>22</food_item_id>
          <success_metrics>
            <satisfaction_index>2.4</satisfaction_index>
            <reorder_probability>0.07122964886156857</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>418</food_item_id>
          <success_metrics>
            <satisfaction_index>0.5</satisfaction_index>
            <reorder_probability>0.5359927534222672</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>352</food_item_id>
          <success_metrics>
            <satisfaction_index>2.7</satisfaction_index>
            <reorder_probability>0.3736407347568347</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>381</food_item_id>
          <success_metrics>
            <satisfaction_index>4.7</satisfaction_index>
            <reorder_probability>0.1319746618976103</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>86</food_item_id>
          <success_metrics>
            <satisfaction_index>3.2</satisfaction_index>
            <reorder_probability>0.837857462073635</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>438</food_item_id>
          <success_metrics>
            <satisfaction_index>4.0</satisfaction_index>
            <reorder_probability>0.25293893966951286</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>216</food_item_id>
          <success_metrics>
            <satisfaction_index>1.9</satisfaction_index>
            <reorder_probability>0.7137953466859113</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>438</food_item_id>
          <success_metrics>
            <satisfaction_index>2.6</satisfaction_index>
            <reorder_probability>0.2317185186093973</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>203</food_item_id>
          <success_metrics>
            <satisfaction_index>2.8</satisfaction_index>
            <reorder_probability>0.13481230094087826</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>398</food_item_id>
          <success_metrics>
            <satisfaction_index>0.7</satisfaction_index>
            <reorder_probability>0.250138891495869</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>370</food_item_id>
          <success_metrics>
            <satisfaction_index>1.8</satisfaction_index>
            <reorder_probability>0.05051601923153992</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>100</food_item_id>
          <success_metrics>
            <satisfaction_index>2.6</satisfaction_index>
            <reorder_probability>0.14504271885311038</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>315</food_item_id>
          <success_metrics>
            <satisfaction_index>4.4</satisfaction_index>
            <reorder_probability>0.5769541693860466</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>75</food_item_id>
          <success_metrics>
            <satisfaction_index>4.7</satisfaction_index>
            <reorder_probability>0.2867991829015012</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>242</food_item_id>
          <success_metrics>
            <satisfaction_index>3.6</satisfaction_index>
            <reorder_probability>0.3414592407772171</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>87</food_item_id>
          <success_metrics>
            <satisfaction_index>4.5</satisfaction_index>
            <reorder_probability>0.10176517454699918</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>101</food_item_id>
          <success_metrics>
            <satisfaction_index>2.2</satisfaction_index>
            <reorder_probability>0.6866745907959261</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>414</food_item_id>
          <success_metrics>
            <satisfaction_index>5.0</satisfaction_index>
            <reorder_probability>0.17337140271308515</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>419</food_item_id>
          <success_metrics>
            <satisfaction_index>4.1</satisfaction_index>
            <reorder_probability>0.8089988226624854</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>13</food_item_id>
          <success_metrics>
            <satisfaction_index>0.1</satisfaction_index>
            <reorder_probability>0.995993537976318</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>180</food_item_id>
          <success_metrics>
            <satisfaction_index>2.9</satisfaction_index>
            <reorder_probability>0.8082529040484794</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>166</food_item_id>
          <success_metrics>
            <satisfaction_index>1.0</satisfaction_index>
            <reorder_probability>0.647015328346593</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>495</food_item_id>
          <success_metrics>
            <satisfaction_index>1.6</satisfaction_index>
            <reorder_probability>0.5650283983748104</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>227</food_item_id>
          <success_metrics>
            <satisfaction_index>3.0</satisfaction_index>
            <reorder_probability>0.4171136971093806</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>261</food_item_id>
          <success_metrics>
            <satisfaction_index>0.9</satisfaction_index>
            <reorder_probability>0.558106076389625</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>289</food_item_id>
          <success_metrics>
            <satisfaction_index>1.8</satisfaction_index>
            <reorder_probability>0.1133093731017698</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>79</food_item_id>
          <success_metrics>
            <satisfaction_index>4.3</satisfaction_index>
            <reorder_probability>0.3312189984693358</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>45</food_item_id>
          <success_metrics>
            <satisfaction_index>3.5</satisfaction_index>
            <reorder_probability>0.9995463113431765</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>38</food_item_id>
          <success_metrics>
            <satisfaction_index>2.0</satisfaction_index>
            <reorder_probability>0.0661194808024731</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>95</food_item_id>
          <success_metrics>
            <satisfaction_index>2.7</satisfaction_index>
            <reorder_probability>0.09428892284522361</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>497</food_item_id>
          <success_metrics>
            <satisfaction_index>4.0</satisfaction_index>
            <reorder_probability>0.6970054969486905</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>202</food_item_id>
          <success_metrics>
            <satisfaction_index>2.9</satisfaction_index>
            <reorder_probability>0.05676282930536314</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>276</food_item_id>
          <success_metrics>
            <satisfaction_index>0.8</satisfaction_index>
            <reorder_probability>0.5383173246714911</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>356</food_item_id>
          <success_metrics>
            <satisfaction_index>2.0</satisfaction_index>
            <reorder_probability>0.9598142042585767</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>242</food_item_id>
          <success_metrics>
            <satisfaction_index>1.7</satisfaction_index>
            <reorder_probability>0.28564601587773863</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>144</food_item_id>
          <success_metrics>
            <satisfaction_index>4.8</satisfaction_index>
            <reorder_probability>0.5201028418257442</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>145</food_item_id>
          <success_metrics>
            <satisfaction_index>2.7</satisfaction_index>
            <reorder_probability>0.16212822262218773</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>405</food_item_id>
          <success_metrics>
            <satisfaction_index>2.5</satisfaction_index>
            <reorder_probability>0.6777550583321038</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>300</food_item_id>
          <success_metrics>
            <satisfaction_index>1.4</satisfaction_index>
            <reorder_probability>0.5334648101064481</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>232</food_item_id>
          <success_metrics>
            <satisfaction_index>0.4</satisfaction_index>
            <reorder_probability>0.7149537667616964</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>132</food_item_id>
          <success_metrics>
            <satisfaction_index>0.5</satisfaction_index>
            <reorder_probability>0.4695640065584229</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>397</food_item_id>
          <success_metrics>
            <satisfaction_index>1.2</satisfaction_index>
            <reorder_probability>0.6840862895157734</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>436</food_item_id>
          <success_metrics>
            <satisfaction_index>1.8</satisfaction_index>
            <reorder_probability>0.27931548129089157</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>255</food_item_id>
          <success_metrics>
            <satisfaction_index>2.1</satisfaction_index>
            <reorder_probability>0.5672996477937792</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>474</food_item_id>
          <success_metrics>
            <satisfaction_index>3.2</satisfaction_index>
            <reorder_probability>0.08577986443022967</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>472</food_item_id>
          <success_metrics>
            <satisfaction_index>3.3</satisfaction_index>
            <reorder_probability>0.725303816962057</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>212</food_item_id>
          <success_metrics>
            <satisfaction_index>3.0</satisfaction_index>
            <reorder_probability>0.3876394801268046</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>198</food_item_id>
          <success_metrics>
            <satisfaction_index>3.4</satisfaction_index>
            <reorder_probability>0.6390785561444158</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>362</food_item_id>
          <success_metrics>
            <satisfaction_index>3.3</satisfaction_index>
            <reorder_probability>0.8252132486353069</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>35</food_item_id>
          <success_metrics>
            <satisfaction_index>3.5</satisfaction_index>
            <reorder_probability>0.20967357518629026</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>408</food_item_id>
          <success_metrics>
            <satisfaction_index>1.6</satisfaction_index>
            <reorder_probability>0.7835793227363766</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>350</food_item_id>
          <success_metrics>
            <satisfaction_index>1.8</satisfaction_index>
            <reorder_probability>0.8462508455873574</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>17</food_item_id>
          <success_metrics>
            <satisfaction_index>1.4</satisfaction_index>
            <reorder_probability>0.7479643727033221</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>382</food_item_id>
          <success_metrics>
            <satisfaction_index>4.7</satisfaction_index>
            <reorder_probability>0.6937952780069992</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>341</food_item_id>
          <success_metrics>
            <satisfaction_index>2.9</satisfaction_index>
            <reorder_probability>0.29748959490929905</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>229</food_item_id>
          <success_metrics>
            <satisfaction_index>2.1</satisfaction_index>
            <reorder_probability>0.31269811924830804</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>476</food_item_id>
          <success_metrics>
            <satisfaction_index>3.4</satisfaction_index>
            <reorder_probability>0.47659185969966333</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>368</food_item_id>
          <success_metrics>
            <satisfaction_index>2.2</satisfaction_index>
            <reorder_probability>0.45580457849754774</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>395</food_item_id>
          <success_metrics>
            <satisfaction_index>2.9</satisfaction_index>
            <reorder_probability>0.9767165485248378</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>210</food_item_id>
          <success_metrics>
            <satisfaction_index>3.7</satisfaction_index>
            <reorder_probability>0.7073411891394281</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>418</food_item_id>
          <success_metrics>
            <satisfaction_index>3.2</satisfaction_index>
            <reorder_probability>0.7539157857031764</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>157</food_item_id>
          <success_metrics>
            <satisfaction_index>1.3</satisfaction_index>
            <reorder_probability>0.6402193046185074</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>222</food_item_id>
          <success_metrics>
            <satisfaction_index>1.4</satisfaction_index>
            <reorder_probability>0.8705014560237312</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>139</food_item_id>
          <success_metrics>
            <satisfaction_index>4.6</satisfaction_index>
            <reorder_probability>0.5261516233530984</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>59</food_item_id>
          <success_metrics>
            <satisfaction_index>4.0</satisfaction_index>
            <reorder_probability>0.5839046844024546</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>375</food_item_id>
          <success_metrics>
            <satisfaction_index>2.8</satisfaction_index>
            <reorder_probability>0.4628709995402227</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>420</food_item_id>
          <success_metrics>
            <satisfaction_index>0.4</satisfaction_index>
            <reorder_probability>0.9250916340423047</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>427</food_item_id>
          <success_metrics>
            <satisfaction_index>4.8</satisfaction_index>
            <reorder_probability>0.8042138300696545</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>435</food_item_id>
          <success_metrics>
            <satisfaction_index>3.1</satisfaction_index>
            <reorder_probability>0.24532424864620717</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>27</food_item_id>
          <success_metrics>
            <satisfaction_index>1.4</satisfaction_index>
            <reorder_probability>0.8175594232901358</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>202</food_item_id>
          <success_metrics>
            <satisfaction_index>0.8</satisfaction_index>
            <reorder_probability>0.11693325419484779</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>318</food_item_id>
          <success_metrics>
            <satisfaction_index>1.0</satisfaction_index>
            <reorder_probability>0.6276915101444528</reorder_probability>
          </success_metrics>
        </item_performance>
        <item_performance>
          <food_item_id>46</food_item_id>
          <success_metrics>
            <satisfaction_index>2.4</satisfaction_index>
            <reorder_probability>0.41720201802622314</reorder_probability>
          </success_metrics>
        </item_performance>
      </menu_analysis>
    </culinary_records>
  </event_administration>
</polar_celebration>');
